name: Terragrunt CI/CD

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  terragrunt:
    name: Terragrunt Apply
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1  # Set your preferred AWS region
      TERRAGRUNT_VERSION: "0.45.3"  # Set your preferred Terragrunt version
      TF_VERSION: "1.4.0"  # Set your preferred Terraform version

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Install Terragrunt
        run: |
          curl -L https://github.com/gruntwork-io/terragrunt/releases/download/v${{ env.TERRAGRUNT_VERSION }}/terragrunt_linux_amd64 -o terragrunt
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/

      - name: List Files (Debugging Step)
        run: ls -R  # This step will list all files in the repository to help identify the correct path.

      - name: Terragrunt Init
        run: terragrunt init
        working-directory: terraform/test  # Update to the correct path of your terragrunt.hcl file

      - name: Terragrunt Plan
        id: plan
        run: terragrunt plan
        continue-on-error: true
        working-directory: terraform/test  # Update to the correct path of your terragrunt.hcl file

      - name: Terragrunt Apply
        if: github.ref == 'refs/heads/main'
        run: terragrunt apply -auto-approve
        working-directory: terraform/test  # Update to the correct path of your terragrunt.hcl file