name: Terragrunt CI/CD

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  terragrunt:
    name: Terragrunt Apply
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      TF_VERSION: "1.4.0"  # Set your preferred Terraform version
      TERRAGRUNT_VERSION: "0.45.3"  # Set your preferred Terragrunt version

    defaults:
      run:
        working-directory: terraform/test  # Set the default working directory

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Set up Terragrunt
        uses: autero1/action-terragrunt@v3
        with:
          terragrunt-version: ${{ env.TERRAGRUNT_VERSION }}

      - name: Terragrunt Init
        run: terragrunt init

      - name: Terragrunt Plan
        id: plan
        run: terragrunt plan
        continue-on-error: true

      - name: Terragrunt Apply
        if: github.ref == 'refs/heads/main'
        run: terragrunt apply -auto-approve